name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - run: make
    - run: make clean
    - run: make fclean
    - run: make re

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run unit tests
      run: make tests_run

    - name: Run coverage
      if: ${{ always() }}
      run: make coverage

  functional-test:
    name: Functional tests
    runs-on: ubuntu-20.04
    container: epitechcontent/epitest-docker
    env:
      LIB_NAME: libmy_malloc.so

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build binary
      run: make

    - name: Export library path
      run: export LD_LIBRARY_PATH=$(PWD)

    - name: Run ls
      run: LD_PRELOAD=$LIB_NAME ls

    - name: Run cat
      run: LD_PRELOAD=$LIB_NAME cat
